- name: Start Mysql Container
  docker_container:
    name: mysql
    image: mysql:5.7
    restart_policy: always
    env:
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: microblog
      MYSQL_DATABASE: microblog
    volumes:
      - ./db/mysql-data:/var/lib/mysql
