# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r requirements.txt
EOF

# RUN python -m venv .venv
# RUN .venv/bin/pip3 install -r requirements.txt

ENV FLASK_APP microblog.py

RUN <<-EOF
    apk upgrade --no-cache
    chmod +x boot.sh
    chown -R microblog:microblog ./
EOF

# RUN chmod +x boot.sh
# RUN chown -R microblog:microblog ./

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]