FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py Makefile .pylintrc pytest.ini boot-test.sh ./

ENV FLASK_APP microblog.py

RUN <<-EOF
    apk --no-cache add --virtual build-dependencies libffi-dev openssl-dev py-pip build-base \
        && pip install --upgrade pip \
        && pip install -r requirements/test.txt \
        && apk del build-dependencies
    apk add --no-cache make
    chmod +x boot-test.sh
EOF
    
USER microblog

ENTRYPOINT ["./boot-test.sh"]