global:
  scrape_interval: "30s"

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9000"]

  - job_name: "flask"
    static_configs:
      - targets: ["microblog:5000"]
        labels:
          instance: flask

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "rules.yml"
