groups:
  - name: More get request than 20
    rules:
      - alert: Between20And25
        expr: flask_http_request_total{method="get", status="200"} > 20 and flask_http_request_total{method="get", status="200"} < 25
        for: 10s
