groups:
  - name: More get request than 20
    rules:
      - alert: Between20And25
        expr: flask_http_request_total{method="get", status="200"} > 20 and flask_http_request_total{method="get", status="200"} < 25
        for: 10s

  - name: Test alarm, create internal server error
    rules:
      - alert: Test alarm, create internal server error
        expr: flask_http_request_duration_seconds_count{instance="flask", method="GET", path="/alarm-check", status="500"} > 0
        for: 10s
        labels:
          severity: critical
