name: Rolling Update of appservers

on: [release]

jobs:
  docker-publish:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  update:
    runs-on: ubuntu-latest
    needs: [docker-publish]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible -y

      - name: Run ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          cd ansible
          ansible-playbook cd_appserver.yml
