name: Running bandit, trivy and dockle

on: [workflow_call]

jobs:
  cs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Bandit
        run: |
          sudo apt-get update
          pip install bandit

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.58.0/trivy_0.58.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.58.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          rm trivy_0.58.0_Linux-64bit.tar.gz

      - name: Install Dockle
        run: |
          wget https://github.com/goodwithtech/dockle/releases/download/v0.4.14/dockle_0.4.14_Linux-64bit.tar.gz
          tar xzvf dockle_0.4.13_Linux-64bit.tar.gz
          sudo mv dockle /usr/local/bin/

      - name: Run Bandit
        run: make bandit-test

      - name: Run Trivy
        run: sudo make trivy-test RELEASE=${{ github.event.release.tag_name }}-prod

      - name: Run Dockle
        env:
          DOCKER_CONTENT_TRUST: 1
        run: make dockle-test RELEASE=${{ github.event.release.tag_name }}-prod
