name: CD Docker Publish

on: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [Unit Tests]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from release tag
        id: extract_version
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo "version=$version" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t miyarima/microblog:${{ env.version }} .

      - name: Push Docker image
        run: |
          docker push miyarima/microblog:${{ env.version }}
