name: CD Docker Publish

on: [release]

jobs:
  test:
    uses: ./.github/workflows/testing.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Prod image
        uses: docker/build-push-action@v6
        env:
              DOCKER_CONTENT_TRUST: 1
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: miyarima/microblog:${{ github.event.release.tag_name }}-prod

      - name: Build Docker Test image
        uses: docker/build-push-action@v6
        env:
              DOCKER_CONTENT_TRUST: 1
        with:
          context: .
          file: ./docker/Dockerfile_test
          push: true
          tags: miyarima/microblog:${{ github.event.release.tag_name }}-test
