name: CD Docker Publish

on: [workflow_call]

jobs:
  test:
    uses: ./.github/workflows/testing.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Prod image
        run: |
          docker build --no-cache -t microblog:${{ github.event.release.tag_name }}-prod -t microblog:prod -f docker/Dockerfile_prod .
          docker tag microblog:${{ github.event.release.tag_name }}-prod miyarima/microblog:${{ github.event.release.tag_name }}-prod

      - name: Push Docker Prod image
        run: docker push miyarima/microblog:${{ github.event.release.tag_name }}-prod

      - name: Build Docker Test image
        run: |
          docker build --no-cache -t microblog:${{ github.event.release.tag_name }}-test -t microblog:test -f docker/Dockerfile_test .
          docker tag microblog:${{ github.event.release.tag_name }}-test miyarima/microblog:${{ github.event.release.tag_name }}-test

      - name: Push Docker Test image
        run: docker push miyarima/microblog:${{ github.event.release.tag_name }}-test
