name: Unit Tests

on: [push, pull_request, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set env var for prometheus
        run: echo "prometheus_multiproc_dir=/tmp" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          make install-test

      - name: Make test
        run: |
          make test
