name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run:
          - python3 -m venv venv
          - source venv/bin/activate
          - make install-test

      - name: Flask db upgrade
        run: flask db upgrade

      - name: Make test
        run: make test
