name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          make install-test

      # python3 -m venv venv
      # source venv/bin/activate
      # - name: Flask db upgrade
      #   run: |
      #     source venv/bin/activate
      #     flask db upgrade
      # source venv/bin/activate

      - name: Make test
        run: |
          make test
