---
- name: Installing Docker.io
  apt:
    name: docker.io
    state: latest

- name: Installing pip3
  apt:
    name: python3-pip
    state: present

- name: Installing Docker with pip3
  pip:
    name: docker
    state: present
